/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.9.0 on Wed Dec  7 19:12:48 2022.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_HW_h_)
#define _HW_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10900 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief LEDBlinkService identifiers */
enum _LEDBlinkService_ids
{
    kLEDBlinkService_service_id = 1,
    kLEDBlinkService_printtext_id = 1,
    kLEDBlinkService_location_id = 2,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name LEDBlinkService
//@{
void printtext(uint8_t c);

void location(uint8_t col, uint8_t row);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _HW_h_
