# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.9.0 on Wed Dec  7 19:13:23 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for LEDBlinkService
class LEDBlinkServiceClient(interface.ILEDBlinkService):
    def __init__(self, manager):
        super(LEDBlinkServiceClient, self).__init__()
        self._clientManager = manager

    def printtext(self, c):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.PRINTTEXT_ID,
                sequence=request.sequence))
        if c is None:
            raise ValueError("c is None")
        codec.write_uint8(c)

        # Send request and process reply.
        self._clientManager.perform_request(request)

    def location(self, col, row):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.LOCATION_ID,
                sequence=request.sequence))
        if col is None:
            raise ValueError("col is None")
        codec.write_uint8(col)
        if row is None:
            raise ValueError("row is None")
        codec.write_uint8(row)

        # Send request and process reply.
        self._clientManager.perform_request(request)



