# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.9.0 on Wed Dec  7 19:13:23 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for LEDBlinkService
class ILEDBlinkService(object):
    SERVICE_ID = 1
    PRINTTEXT_ID = 1
    LOCATION_ID = 2

    def printtext(self, c):
        raise NotImplementedError()

    def location(self, col, row):
        raise NotImplementedError()


