# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.9.0 on Wed Dec  7 16:38:36 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for LEDBlinkService
class LEDBlinkServiceService(erpc.server.Service):
    def __init__(self, handler):
        super(LEDBlinkServiceService, self).__init__(interface.ILEDBlinkService.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.ILEDBlinkService.PRINTTEXT_ID: self._handle_printtext,
                interface.ILEDBlinkService.LOCATION_ID: self._handle_location,
            }

    def _handle_printtext(self, sequence, codec):
        # Read incoming parameters.
        led = codec.read_uint8()

        # Invoke user implementation of remote function.
        self._handler.printtext(led)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.ILEDBlinkService.SERVICE_ID,
            request=interface.ILEDBlinkService.PRINTTEXT_ID,
            sequence=sequence))

    def _handle_location(self, sequence, codec):
        # Read incoming parameters.
        led = codec.read_uint8()

        # Invoke user implementation of remote function.
        self._handler.location(led)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.ILEDBlinkService.SERVICE_ID,
            request=interface.ILEDBlinkService.LOCATION_ID,
            sequence=sequence))


